module.exports = {
    EMAIL_NOT_PROVIDED: "Email not provided",
    EMAIL_NOT_FOUND: "Email not found",
    EMAIL_INVALID_FORMAT: "Email in invalid format",
    EMAIL_TAKEN: "User with specified email already exists",
    PASSWORDS_DO_NOT_MATCH: "Passwords do not match",
    PASSWORD_NOT_PROVIDED: "Password not provided",
    INCORRECT_PASSWORD: "Incorrect password",
    FAILED_TO_SEND_EMAIL: "Failed to send email",
    USER_ROLE_NOT_FOUND: "User role not found",
    USER_NOT_FOUND: "User not found",
    PASSWORD_TOKEN_EXPIRED: "The password reset token has expired",
    INVALID_TOKEN: "Token is not valid",
    TOKEN_EXPIRED: "The Token has expired",
    PROJECT_NOT_FOUND: "Project not found",
    INVALID_PROJECT_ID: "Invalid project id",
    PROJECT_NAME_NOT_PROVIDED: "Project name is not provided.",
    PROJECT_DESCRIPTION_NOT_PROVIDED: "Project description is not provided.",
    PROJECT_START_DATE_INVALID_FORMAT: "Invalid format for project start date.",
    PROJECT_START_DATE_NOT_PROVIDED: "Project start date is not provided.",
    PROJECT_END_DATE_INVALID_FORMAT: "Invalid format for project end date.",
    PROJECT_END_DATE_NOT_PROVIDED: "Project end date is not provided.",
    PROJECT_DEVELOPER_USER_ID_NOT_PROVIDED: "Developer user ID is not provided.",
    PROJECT_DEVELOPER_FULL_TIME_NOT_PROVIDED: "Full-time status of developer is not provided.",
    PROJECT_DEVELOPERS_NOT_PROVIDED: "Project developers are not provided.",
    PROJECT_TYPE_NOT_PROVIDED: "Project type is not provided.",
    PROJECT_TYPE_INVALID: "Invalid project type.",
    PROJECT_HOURLY_RATE_INVALID_FORMAT: "Invalid format for project hourly rate.",
    PROJECT_HOURLY_RATE_NOT_PROVIDED: "Project hourly rate is not provided.",
    PROJECT_VALUE_INVALID_FORMAT: "Invalid format for project value.",
    PROJECT_VALUE_NOT_PROVIDED: "Project value is not provided.",
    PROJECT_ACTUAL_END_DATE_INVALID_FORMAT: "Project end date is in incorrect format",
    PROJECT_SALES_CHANNEL_EMPTY: "Sales channel is empty.",
    DATA_NOT_FOUND: "Data not found",
    


}